---
- name: Reload WireGuard connection
  ansible.builtin.shell:
    cmd: >-
      nmcli connection load /etc/NetworkManager/system-connections/{{ wireguard_connection_name }}.nmconnection &&
      nmcli device reapply {{ wireguard_connection_name }}
