---
- name: Install WireGuard and required packages
  ansible.builtin.dnf:
    name:
      - wireguard-tools
    state: present
    enablerepo: "powertools"

- name: Ensure wireguard configuration file is present
  ansible.builtin.template:
    src: wg0.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/{{ wireguard_connection_name }}.nmconnection
    mode: "0600"
    owner: root
    group: root
  notify:
    - Reload WireGuard connection

- name: Configure firewall to allow WireGuard traffic
  ansible.posix.firewalld:
    service: wireguard
    permanent: true
    state: enabled
    immediate: true
    zone: "{{ wireguard_firewall_zone }}"
